#cloud-config

hostname: dev001

ssh_pwauth: False

package_update: true
package_upgrade: true
packages:
  - ssh-import-id
  - tree
  - git
  - gh
  - vim
  - sqlite3
  - python3
  - tmux
  - batcat
  - fzf

users:
  - name: mattw1285
    gecos: "Matt"
    groups: 
      - sudo
    lock_passwd: true
    ssh_import_id: 
      - gh:mattw1285


runcmd:
  - systemctl enable ssh
