" --- 1. General Setttings ---
set nocompatible
set hidden
set mouse=a
syntax on

set background=light
colorscheme delek

set number
highlight LineNr guifg=#808080 ctermfg=244

set expandtab
set tabstop=4
set shiftwidth=4

set colorcolumn=80
highlight ColorColumn guibg=#808080 ctermbg=244 


let g:netrw_winsize = 20

let g:netrw_altv = 1
let g:netrw_banner = 0
let g:netrw_liststyle = 3

augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * if argc() == 0 | Vexplore | endif
augroup END
